### PR TITLE
change num version in cargo toml

### PR DESCRIPTION
**Pull request by maxtnuk**
i just change num crate version 
because Array struct can not use num::Complex in element 
so here is my request

### CODE REVIEW

**Comment by 9prady9** [comment]
@maxtnuk the current crate release 3.6.1 works with 3.6.4 of ArrayFire, I have ran it more than couple of times in the past month or so. What is the error you are seeing it for `num=0.1` ?

**Comment by maxtnuk** [comment]
@9prady9 
here i got error when num=0.1 (version: 3.6.1)
error[E0277]: the trait bound `num_complex::Complex<f64>: arrayfire::util::HasAfEnum` is not satisfied
  --> src/compo.rs:21:5
   |
21 |     data: Array<Complex<f64>>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `arrayfire::util::HasAfEnum` is not implemented for `num_complex::Complex<f64>`
   |
   = note: required by `arrayfire::array::Array`

**Comment by 9prady9** [comment]
I have just tried this on Arch linux with rust 1.36.0 and the crate built just fine like I said earlier. Also, [here](https://github.com/arrayfire/arrayfire-rust/blob/master/src/util.rs#L220) is the HasAfEnum trait implementation for `Complex<f64>`. So, I am not sure why you are getting this on your end.

**Comment by 9prady9** [comment]
This is probably related to https://github.com/arrayfire/arrayfire-rust/issues/201
